apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: akoricansky/ambulance-ufe
  newName: akoricansky/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20250405.1227 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
